@urlprincipal =http://localhost:4000
@otavariable= https://example.com/comments


GET {{urlprincipal}}/producto/615bb8a71bf7bbc354500ceb
###

GET {{urlprincipal}}/producto/615bb8a71bf7bbc354500cec

###
GET {{urlprincipal}}/productos

### crear un producto 
POST {{urlprincipal}}/productos
Content-Type: application/json

{
    "nombre": "MANZANA",
    "id":11,   
    "descripcion": "manzana desde el POST en producto",
    "precio" : 7.25,
}

### crear un producto 
POST {{urlprincipal}}/producto
Content-Type: application/json

{   "id" : 4, 
    "nombre" : "FRAMBUESA",
    "descripcion" : "FRAMBUESA, RUBUS IDAEUS / ROSACEAE",
    "poster_path" : "/4.jpg",
    "precio" : 7.25 
}

### eliminar un producto
DELETE {{urlprincipal}}/productos/615cf377cdaf0aa17bf40ac2

### actualizar 
PUT {{urlprincipal}}/productos/615bc0c8689ceb0baa12339e
Content-Type: application/json

{
    "nombre" : "manzana"
}
